
2025-09-18 18:20:01,935 - INFO - Base de datos configurada correctamente en mysql+pymysql://root:admin@localhost:3306/academiacert
2025-09-18 18:20:46,211 - INFO - Base de datos configurada correctamente en mysql+pymysql://root:admin@localhost:3306/academiacert
2025-09-18 18:23:26,556 - INFO - Base de datos configurada correctamente en mysql+pymysql://root:admin@localhost:3306/academiacert
2025-09-18 18:23:26,717 - INFO - Iniciando aplicación...
2025-09-18 18:23:27,097 - INFO - Tablas verificadas/creadas correctamente.
2025-09-18 18:23:32,817 - INFO - Entrando al menú de docentes
2025-09-18 18:24:33,286 - INFO - Docente creado con ID: 3
2025-09-18 18:25:27,285 - INFO - Listando docentes...
2025-09-18 18:31:58,715 - ERROR - Error inesperado en buscar_docente: 'Docente' object has no attribute 'número_identificacion'
Traceback (most recent call last):
  File "c:\Users\TP\Desktop\programacion\proyectos\Certificacion\proyecto modulo 4\utils\decorators.py", line 11, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\TP\Desktop\programacion\proyectos\Certificacion\proyecto modulo 4\main_t\main_docente.py", line 35, in buscar_docente
    m_docente(docente)
  File "c:\Users\TP\Desktop\programacion\proyectos\Certificacion\proyecto modulo 4\view\docentes_view.py", line 36, in mostrar_docente
    tabla.add_row([campo, getattr(docente, campo)])
                          ^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Docente' object has no attribute 'número_identificacion'. Did you mean: 'numero_identificacion'?
2025-09-18 18:49:35,854 - INFO - Saliendo de la aplicación...
2025-09-18 18:55:42,453 - INFO - Base de datos configurada correctamente en mysql+pymysql://root:admin@localhost:3306/academiacert
2025-09-18 18:55:42,740 - INFO - Iniciando aplicación...
2025-09-18 18:55:42,991 - INFO - Tablas verificadas/creadas correctamente.
2025-09-18 18:55:46,956 - INFO - Entrando al menu de docentes
